name = "agentflow"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "agentflow"
compatibility_flags = ["nodejs_compat"]
