name = "agent-flow"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
name = "agent-flow"
pages_build_output_dir = ".next"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://dhjllodeisqiiipjckeb.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoamxsb2RlaXNxaWlpcGpja2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODk1NzIsImV4cCI6MjA2ODM2NTU3Mn0.1n9JVWIPcfjRjh3N47x1U4lfUukFcV7hqr7H6bh37iw"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51RTP1RADcDx0HlloXRWN1wYrD3UTrBEzJweDdjVsvP7SKhqcmDP6KL79xGbuTZGB4OuIFcvU3wxbg1CnjJ3PzNrQ002wtgPEnQ"
NEXT_PUBLIC_APP_URL = "https://agentflow.pages.dev"
NEXT_PUBLIC_AI_API_KEY = "sk-4b7f1bd6704948b488d54c71187e7273"
NEXT_PUBLIC_AI_BASE_URL = "https://api.deepseek.com/v1"
NEXT_PUBLIC_AI_MODEL = "deepseek-chat"
