name = "agentflow"
main = ".next/standalone/server.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
name = "agentflow"

[env.staging]
name = "agentflow-staging"

[vars]
NEXT_PUBLIC_APP_URL = "https://agentflow.pages.dev"

[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "your-staging-kv-namespace-id"
