name = "agent-flow"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
name = "agent-flow"

[[env.production.routes]]
pattern = "/*"
zone_name = "agentflow.pages.dev"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
